name: Pulumi Destroy Staging

on:
  push:
    branches:
      - dangerously-destroy-all-staging-infrastructure

jobs:
  up:
    name: Destroy Staging
    uses: ./.github/workflows/pulumi-runner.yml
    with:
      command: destroy
      comment-on-pr: false
      gh-role-arn: arn:aws:iam::075109709139:role/sk-infra-github-oidc-role-e6eab36
      s3-bucket-uri: s3://sk-infra-pulumi-s3-states-bucket-0f5edcd
      stack-name: sk-infra.staging
    secrets: inherit
