name: Pulumi Preview Staging

on:
  pull_request:
    branches:
      - develop
      - staging

jobs:
  preview:
    name: Preview Staging
    uses: ./.github/workflows/pulumi-runner.yml
    with:
      gh-role-arn: arn:aws:iam::646878943557:role/sk-infra-github-oidc-role-7e7deb4
      stack-name: sk-infra.staging
      s3-bucket-uri: s3://sk-infra-pulumi-s3-states-bucket-803f20f
      command: preview
    secrets: inherit
